name: Rubocop
on: 
  push:
    paths:
      - "**/*.rb"
      - "profanity.rb"
  pull_request:
    paths:
      - "**/*.rb"
      - "profanity.rb"

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.3']
    name: Run Rubocop on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: step-security/changed-files@3dbe17c78367e7d60f00d78ae6781a35be47b4a1
        with:
          files: |
            **/*.rb
            profanity.rb
        
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: false
      - name: Install ruby gem dependencies with bundler
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      - run: bundle install
      - name: Rubocop
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            bundle exec rubocop $file
          done
